package com.kots.sidim.web.model;

// Generated 27/08/2012 21:21:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Bairro generated by hbm2java
 */
@Entity
@Table(name = "BAIRRO")
@ManagedBean(name = "bairro")
public class Bairro implements java.io.Serializable {

	private int idBairro;
	private Cidade cidade;
	private String nome;
	private String padrao;
	private Set<PendenciaCadastroImoveis> pendenciaCadastroImoveis = new HashSet<PendenciaCadastroImoveis>(0);
	private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);
	private Set<Perfil> perfils = new HashSet<Perfil>(0);
	private Set<Imovel> imovels = new HashSet<Imovel>(0);

	public Bairro() {
	}

	public Bairro(int idBairro, Cidade cidade, String nome, String padrao) {
		this.idBairro = idBairro;
		this.cidade = cidade;
		this.nome = nome;
		this.padrao = padrao;
	}

	public Bairro(int idBairro, Cidade cidade, String nome, String padrao,
			Set<PendenciaCadastroImoveis> pendenciaCadastroImoveis,
			Set<Funcionario> funcionarios, Set<Perfil> perfils,
			Set<Imovel> imovels) {
		this.idBairro = idBairro;
		this.cidade = cidade;
		this.nome = nome;
		this.padrao = padrao;
		this.pendenciaCadastroImoveis = pendenciaCadastroImoveis;
		this.funcionarios = funcionarios;
		this.perfils = perfils;
		this.imovels = imovels;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="SEQ_BAIRRO")
	@SequenceGenerator(name="SEQ_BAIRRO", sequenceName = "SEQ_BAIRRO", allocationSize=1)
	@Column(name = "ID_BAIRRO", unique = true, nullable = false, precision = 10, scale = 0)
	public int getIdBairro() {
		return this.idBairro;
	}

	public void setIdBairro(int idBairro) {
		this.idBairro = idBairro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CIDADE", nullable = false)
	public Cidade getCidade() {
		return this.cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

	@Column(name = "NOME", nullable = false, length = 70)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "PADRAO", nullable = false, length = 1)
	public String getPadrao() {
		return this.padrao;
	}

	public void setPadrao(String padrao) {
		this.padrao = padrao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bairro")
	public Set<PendenciaCadastroImoveis> getPendenciaCadastroImoveis() {
		return this.pendenciaCadastroImoveis;
	}

	public void setPendenciaCadastroImoveis(
			Set<PendenciaCadastroImoveis> pendenciaCadastroImoveis) {
		this.pendenciaCadastroImoveis = pendenciaCadastroImoveis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bairro")
	public Set<Funcionario> getFuncionarios() {
		return this.funcionarios;
	}

	public void setFuncionarios(Set<Funcionario> funcionarios) {
		this.funcionarios = funcionarios;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "bairros")
	public Set<Perfil> getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set<Perfil> perfils) {
		this.perfils = perfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bairro")
	public Set<Imovel> getImovels() {
		return this.imovels;
	}

	public void setImovels(Set<Imovel> imovels) {
		this.imovels = imovels;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (idBairro ^ (idBairro >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Bairro))
			return false;
		Bairro other = (Bairro) obj;
		if (idBairro != other.idBairro)
			return false;
		return true;
	}

	
	
}
