package com.kots.sidim.web.model;

// Generated 27/08/2012 21:21:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "CLIENTE")
@ManagedBean(name = "cliente")
public class Cliente implements java.io.Serializable {

	private String login;
	private Cidade cidade;
	private String nome;
	private String email;
	private String telefone;
	private String senha;
	private Set<Perfil> perfils = new HashSet<Perfil>(0);
	private Set<InteresseCliente> interesseClientes = new HashSet<InteresseCliente>(0);

	public Cliente() {
	}

	public Cliente(String login, String nome, String email, String senha) {
		this.login = login;
		this.nome = nome;
		this.email = email;
		this.senha = senha;
	}

	public Cliente(String login, Cidade cidade, String nome, String email, String telefone, String senha, Set<Perfil> perfils,
			Set<InteresseCliente> interesseClientes) {
		this.login = login;
		this.cidade = cidade;
		this.nome = nome;
		this.email = email;
		this.telefone = telefone;
		this.senha = senha;
		this.perfils = perfils;
		this.interesseClientes = interesseClientes;
	}

	@Id
	@Column(name = "LOGIN", unique = true, nullable = false, length = 15)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CIDADE")
	public Cidade getCidade() {
		return this.cidade;
	}

	public void setCidade(Cidade cidade) {
		this.cidade = cidade;
	}

	@Column(name = "NOME", nullable = false, length = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "EMAIL", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TELEFONE", length = 14)
	public String getTelefone() {
		return this.telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "SENHA", nullable = false, length = 20)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<Perfil> getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set<Perfil> perfils) {
		this.perfils = perfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<InteresseCliente> getInteresseClientes() {
		return this.interesseClientes;
	}

	public void setInteresseClientes(Set<InteresseCliente> interesseClientes) {
		this.interesseClientes = interesseClientes;
	}

}
