package com.kots.sidim.web.model;

// Generated 27/08/2012 21:21:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TipoImovel generated by hbm2java
 */
@Entity
@Table(name = "TIPO_IMOVEL")
@ManagedBean(name = "tipoImovel")
public class TipoImovel implements java.io.Serializable {

	private int idTipoImovel;
	private String descricao;
	
	private Set<PendenciaCadastroImoveis> pendenciaCadastroImoveis = new HashSet<PendenciaCadastroImoveis>(0);
	private Set<Perfil> perfils = new HashSet<Perfil>(0);
	private Set<Imovel> imovels = new HashSet<Imovel>(0);
	 
	public TipoImovel() {
	}

	public TipoImovel(int idTipoImovel, String descricao) {
		this.idTipoImovel = idTipoImovel;
		this.descricao = descricao;
	}

	public TipoImovel(int idTipoImovel, String descricao, Set<PendenciaCadastroImoveis> pendenciaCadastroImoveis, Set<Perfil> perfils, Set<Imovel> imovels) {
		this.idTipoImovel = idTipoImovel;
		this.descricao = descricao;
		this.pendenciaCadastroImoveis = pendenciaCadastroImoveis;
		this.perfils = perfils;
		this.imovels = imovels;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_TIPO_IMOVEL")
	@SequenceGenerator(name = "SEQ_TIPO_IMOVEL", sequenceName = "SEQ_TIPO_IMOVEL", allocationSize = 1)
	@Column(name = "ID_TIPO_IMOVEL", unique = true, nullable = false, precision = 4, scale = 0)
	public int getIdTipoImovel() {
		return this.idTipoImovel;
	}

	public void setIdTipoImovel(int idTipoImovel) {
		this.idTipoImovel = idTipoImovel;
	}

	@Column(name = "DESCRICAO", nullable = false, length = 50)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoImovel")
	public Set<PendenciaCadastroImoveis> getPendenciaCadastroImoveis() {
		return this.pendenciaCadastroImoveis;
	}

	public void setPendenciaCadastroImoveis(Set<PendenciaCadastroImoveis> pendenciaCadastroImoveis) {
		this.pendenciaCadastroImoveis = pendenciaCadastroImoveis;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "tipoImovels")
	public Set<Perfil> getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set<Perfil> perfils) {
		this.perfils = perfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoImovel")
	public Set<Imovel> getImovels() {
		return this.imovels;
	}

	public void setImovels(Set<Imovel> imovels) {
		this.imovels = imovels;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + idTipoImovel;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof TipoImovel))
			return false;
		TipoImovel other = (TipoImovel) obj;
		if (idTipoImovel != other.idTipoImovel)
			return false;
		return true;
	}

}
